global:
  scrape_interval: 10s
  
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
       - targets: ['localhost:9090']
  - job_name: 'node_exporter_master'
    scrape_interval: 5s
    static_configs:
       - targets: ['localhost:9100']
  - job_name: 'node_exporter_client1'
    scrape_interval: 5s
    static_configs:
       - targets: ['192.168.1.51.:9100']
  - job_name: 'node_exporter_client2'
    scrape_interval: 5s
    static_configs:
       - targets: ['192.168.1.52:9100']