version: '3.5'
services: 
  web-server:
    image: nginx:stable
    container_name: mynginx
    volumes:
      - '/opt/web/html:/var/www/html'
      - '/opt/web/pics:/var/www/pictures'
      - 'nginx-config:/var/www/config'
    environment: 
      - 'NGINX_HOST=web.penul4ik.ru'
      - 'NGINX_PORT=80'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
volumes:
  nginx-config:
networks:
  default:
    driver: bridge
    name: webnet
