{
 "title": "Mainhost Resources Usage Konovalenko for OTUS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", mode!=\"idle\", job=\"node\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\",job=\"node\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"node\"} - node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"node\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Trafic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} recive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"node\",instance=\"localhost:9100\"}",
     "legendFormat": "LA 1 min"
    },
    {
     "expr": "node_load5{job=\"node\",instance=\"localhost:9100\"}",
     "legendFormat": "LA 5 min"
    },
    {
     "expr": "node_load15{job=\"node\",instance=\"localhost:9100\"}",
     "legendFormat": "LA 15 min"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\",device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{job=\"node\",instance=\"localhost:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}